export const SET_START_GAME="SET_START_GAME";
export const SET_INSTRUCTION_EXPAND="SET_INSTR_EXP";
export const SET_GUESS="SET_GUESS";

export const DECK = {
    FETCH_SUCCESS: "FETCH_DECK_SUCCESS",
    FETCH_ERROR: "FETCH_DECK_ERROR",
    DRAW_SUCCESS: "DRAW_DECK_SUCCESS",
    DRAW_ERROR: "DRAW_DECK_ERROR"
}
